name: Generate CF IP

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List files
        run: ls -R .

      - name: Run Python script
        run: python scripts/generate_ip_country.py

      - name: Show output file
        run: |
          echo "=== cf_ipv4.txt 内容 ==="
          cat cf_ipv4.txt || echo "文件不存在"

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          if git status --porcelain | grep -q "cf_ipv4.txt"; then
            git add cf_ipv4.txt
            git commit -m "Update cf_ipv4.txt [auto]"
            git push
          else
            echo "没有变化，不提交"
          fi
